language: java

install: mvn clean install -DskipTests=true ; 

jdk:
  - oraclejdk8

deploy:
   edge: true
   provider: cloudfoundry
   username: rajiv.270992@gmail.com  
   password: Pivotal.io
   api: https://api.run.pivotal.io
   organization: sitesurveyorg
   space: development
